"use client";
import { useEffect, useState } from "react";
import { loadStripe } from "@stripe/stripe-js";
import { Elements, PaymentElement, useElements, useStripe } from "@stripe/react-stripe-js";
import { LockKeyhole, ShieldCheck } from "lucide-react";
import { useParams, useRouter } from "next/navigation";
import api from "@/lib/axios";
import { PublicHeader } from "@/components/MarketLocalUI";
const stripeKey=process.env.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY;const stripePromise=stripeKey?loadStripe(stripeKey):null;
function CheckoutForm({orderId}:{orderId:string}){const stripe=useStripe();const elements=useElements();const router=useRouter();const [loading,setLoading]=useState(false);const [ready,setReady]=useState(false);const [error,setError]=useState("");const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!stripe||!elements||!ready)return;setLoading(true);setError("");const result=await stripe.confirmPayment({elements,redirect:"if_required",confirmParams:{return_url:`${window.location.origin}/commandes/${orderId}`}});if(result.error)setError(result.error.message||"Le paiement a échoué.");else router.push(`/commandes/${orderId}`);setLoading(false);};return <form onSubmit={submit}><div className="rounded-2xl border border-slate-100 bg-white p-5"><PaymentElement onReady={()=>setReady(true)} onLoadError={(e)=>setError(e.error?.message||"Impossible de charger le formulaire de paiement.")} /></div>{error&&<div className="mt-3 rounded-xl bg-red-50 p-3 text-xs text-red-600">{error}</div>}<button disabled={!stripe||!ready||loading} className="mt-4 flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-green-600 text-xs font-extrabold text-white hover:bg-green-700 disabled:bg-slate-200"><LockKeyhole size={15}/>{loading?"Paiement en cours...":"Payer la commande"}</button></form>}
export default function PaiementPage(){const id=String(useParams().id);const [secret,setSecret]=useState<string|null>(null);const [error,setError]=useState("");useEffect(()=>{api.post(`/orders/${id}/payer`).then(r=>setSecret(r.data.client_secret)).catch(e=>setError(e.response?.data?.message||"Impossible d'initialiser le paiement."));},[id]);return <div className="min-h-screen bg-[#f7faf8]"><PublicHeader/><main className="mx-auto max-w-2xl px-4 py-10"><div className="mb-6 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-green-100 text-green-600"><ShieldCheck size={23}/></div><p className="mt-4 text-[10px] font-extrabold uppercase tracking-[0.18em] text-green-600">Paiement sécurisé</p><h1 className="mt-1 text-3xl font-black">Finaliser la commande #{id}</h1><p className="mt-2 text-sm text-slate-500">Vos données bancaires sont traitées directement par Stripe.</p></div>{!stripePromise?<div className="rounded-2xl bg-white p-6 text-center text-xs text-red-600 shadow-sm">La clé publique Stripe n'est pas configurée dans le frontend.</div>:error?<div className="rounded-2xl bg-white p-6 text-center text-xs text-red-600 shadow-sm">{error}</div>:!secret?<div className="rounded-2xl bg-white p-10 text-center text-xs text-slate-400 shadow-sm">Préparation du paiement...</div>:<Elements stripe={stripePromise} options={{clientSecret:secret}}><CheckoutForm orderId={id}/></Elements>}<div className="mt-5 flex justify-center gap-2 text-[10px] text-slate-400"><ShieldCheck size={13} className="text-green-600"/> Paiement protégé · Stripe</div></main></div>}