"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowRight, Leaf, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useAppDispatch, useAppSelector } from "@/lib/hooks";
import { login } from "@/features/auth/authSlice";
import { Logo } from "@/components/MarketLocalUI";

export default function LoginPage() {
  const dispatch = useAppDispatch(); const router = useRouter(); const { status, error } = useAppSelector((s) => s.auth); const [email, setEmail] = useState(""); const [password, setPassword] = useState("");
  const submit = async (e: React.FormEvent) => { e.preventDefault(); const r = await dispatch(login({ email, password })); if (login.fulfilled.match(r)) router.push("/dashboard"); };
  return <div className="min-h-screen bg-[#f7faf8] lg:grid lg:grid-cols-[1.05fr_.95fr]"><div className="relative hidden overflow-hidden bg-[#073c28] p-10 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -right-28 -top-20 h-80 w-80 rounded-full bg-green-500/20" /><div className="absolute -bottom-32 -left-24 h-96 w-96 rounded-full bg-lime-300/10" /><div className="relative"><div className="mb-16"><Logo compact /></div><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-[10px] font-bold"><Leaf size={13} /> Une marketplace plus humaine</span><h1 className="mt-5 max-w-lg text-5xl font-black leading-tight">Le meilleur du local, <span className="text-lime-200">en un clic.</span></h1><p className="mt-5 max-w-md text-sm leading-6 text-white/70">Retrouvez vos produits préférés, suivez vos commandes et découvrez des vendeurs passionnés.</p></div><div className="relative flex gap-6 text-xs text-white/60"><span className="inline-flex items-center gap-2"><ShieldCheck size={15} /> Paiement sécurisé</span><span className="inline-flex items-center gap-2"><Leaf size={15} /> Produits locaux</span></div></div><div className="flex min-h-screen items-center justify-center px-5 py-10 sm:px-8 lg:px-16"><div className="w-full max-w-md"><div className="mb-10 lg:hidden"><Logo /></div><div className="mb-8"><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-green-600">Bienvenue</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-900">Se connecter</h2><p className="mt-2 text-sm text-slate-500">Accédez à votre espace MarketLocal.</p></div><form onSubmit={submit} className="space-y-4 rounded-3xl border border-slate-100 bg-white p-6 shadow-[0_15px_50px_rgba(15,23,42,.06)] sm:p-8"><Field icon={<Mail size={16} />} label="Email" value={email} onChange={setEmail} type="email" placeholder="vous@exemple.com" /><Field icon={<LockKeyhole size={16} />} label="Mot de passe" value={password} onChange={setPassword} type="password" placeholder="••••••••" />{error && <div className="rounded-xl bg-red-50 px-3 py-2 text-xs text-red-600">{error}</div>}<button disabled={status === "loading"} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-green-600 text-xs font-extrabold text-white shadow-sm hover:bg-green-700 disabled:bg-slate-200">{status === "loading" ? "Connexion..." : "Se connecter"}<ArrowRight size={15} /></button></form><p className="mt-5 text-center text-xs text-slate-500">Pas encore de compte ? <Link href="/register" className="font-bold text-green-600">Créer un compte</Link></p></div></div></div>;
}
function Field({ icon, label, value, onChange, type, placeholder }: { icon: React.ReactNode; label: string; value: string; onChange: (v: string) => void; type: string; placeholder: string }) { return <label className="block text-xs font-bold text-slate-600">{label}<span className="relative mt-1 block"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400">{icon}</span><input required type={type} value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-slate-200 pl-10 pr-3 text-xs font-normal outline-none transition focus:border-green-300 focus:ring-4 focus:ring-green-50" /></span></label>; }
