"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Check, ChevronRight, CircleDollarSign, Package, Percent, ShoppingBag, ShoppingCart, Store, TrendingUp, Users, X } from "lucide-react";
import { useRouter } from "next/navigation";
import { useAppDispatch, useAppSelector } from "@/lib/hooks";
import { fetchMe } from "@/features/auth/authSlice";
import { fetchMyShop } from "@/features/shop/shopSlice";
import { fetchAllShops, fetchStats, refuseShop, validateShop } from "@/features/admin/adminSlice";
import api from "@/lib/axios";
import DashboardLayout from "@/components/DashboardLayout";
import { money, StatusBadge } from "@/components/MarketLocalUI";

interface ShopStats { produits_en_ligne:number; produits_en_rupture:number; total_commandes:number; commandes_en_cours:number; chiffre_affaires_net_30j:number; chiffre_affaires_brut:number; chiffre_affaires_net:number; taux_commission:number; }
interface ShopOrder { id:number; statut:string; created_at:string; buyer:{name:string}; items:{id:number;quantite:number;product:{nom:string}}[]; total?:string; }

export default function DashboardPage(){const dispatch=useAppDispatch();const router=useRouter();const {user,token}=useAppSelector(s=>s.auth);useEffect(()=>{if(!token){router.push("/login");return;}if(!user)dispatch(fetchMe());},[token,user,dispatch,router]);if(!user)return <div className="min-h-screen bg-[#f7faf8]"/>;return <DashboardLayout><div className="mb-7 flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-green-600">{user.role==="admin"?"Administration":user.role==="vendeur"?"Espace vendeur":"Espace acheteur"}</p><h1 className="mt-1 text-3xl font-black tracking-tight text-slate-900">Bonjour {user.name.split(" ")[0]} 👋</h1><p className="mt-1 text-sm text-slate-500">Voici un aperçu de votre activité sur MarketLocal.</p></div><Link href="/catalogue" className="inline-flex items-center gap-2 rounded-xl bg-green-600 px-4 py-2.5 text-xs font-extrabold text-white hover:bg-green-700">Explorer le catalogue <ArrowUpRight size={14}/></Link></div>{user.role==="acheteur"?<Buyer/>:user.role==="vendeur"?<Seller/>:<Admin/>}</DashboardLayout>}

function Buyer(){const [orders,setOrders]=useState<any[]>([]);useEffect(()=>{api.get("/orders/mine").then(r=>setOrders(r.data)).catch(()=>setOrders([]));},[]);const inProgress=orders.filter(o=>["en_attente","payee","expediee"].includes(o.statut)).length;const delivered=orders.filter(o=>o.statut==="livree").length;return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-3"><Metric icon={<ShoppingBag size={18}/>} label="Commandes en cours" value={inProgress}/><Metric icon={<Package size={18}/>} label="Commandes livrées" value={delivered}/><Metric icon={<CircleDollarSign size={18}/>} label="Achats" value={orders.length}/></div><div className="grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><Panel title="Mes commandes récentes" action={<Link href="/mes-commandes" className="text-[11px] font-bold text-green-600">Voir tout</Link>}>{orders.length===0?<Empty message="Vous n'avez pas encore passé de commande." href="/catalogue"/>:<div className="divide-y divide-slate-100">{orders.slice(0,5).map(o=><Link key={o.id} href={`/commandes/${o.id}`} className="flex items-center justify-between gap-3 py-3"><div className="min-w-0"><div className="flex items-center gap-2"><p className="text-xs font-bold">Commande #{o.id}</p><StatusBadge status={o.statut}/></div><p className="mt-1 truncate text-[10px] text-slate-400">{o.items.map((i:any)=>i.product.nom).join(", ")}</p></div><div className="text-right"><p className="text-xs font-black">{money(o.total)}</p><ChevronRight size={14} className="ml-auto mt-1 text-slate-300"/></div></Link>)}</div>}</Panel><Panel title="Accès rapides"><div className="grid grid-cols-2 gap-2"><Quick href="/catalogue" icon={<Store size={16}/>} label="Catalogue"/><Quick href="/panier" icon={<ShoppingCart size={16}/>} label="Mon panier"/><Quick href="/mes-commandes" icon={<Package size={16}/>} label="Commandes"/><Quick href="/profil" icon={<Users size={16}/>} label="Mon profil"/></div></Panel></div></div>}

function Seller(){const dispatch=useAppDispatch();const {shop}=useAppSelector(s=>s.shop);const [stats,setStats]=useState<ShopStats|null>(null);const [orders,setOrders]=useState<ShopOrder[]>([]);useEffect(()=>{dispatch(fetchMyShop());api.get("/shop/stats").then(r=>setStats(r.data)).catch(()=>{});api.get("/shop/orders").then(r=>setOrders(r.data)).catch(()=>{});},[dispatch]);const pending=orders.filter(o=>["payee","en_attente"].includes(o.statut));const values=useMemo(()=>[28,34,30,48,43,65,56,74,60,78,70,88],[]);return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Ventes nettes (30j)" value={money(stats?.chiffre_affaires_net_30j)} icon={<TrendingUp size={18}/>} trend="+12%"/><Metric label="Commandes" value={stats?.total_commandes??0} icon={<ShoppingCart size={18}/>} trend="+6"/><Metric label="Produits en ligne" value={stats?.produits_en_ligne??shop?.products?.length??0} icon={<Package size={18}/>} trend="+2"/><Metric label="Commission" value={`${Number(stats?.taux_commission||0).toFixed(1)}%`} icon={<Percent size={18}/>} /></div>{!shop&&<Notice title="Votre boutique n'est pas encore créée" text="Créez votre boutique pour commencer à vendre." href="/shop/create" action="Créer ma boutique"/>}{shop&&<Notice title={shop.nom} text={shop.statut==="valide"?"Votre boutique est active et visible dans le catalogue.":shop.statut==="en_attente"?"Votre demande est en attente de validation.":"Votre demande de boutique a été refusée."} tone={shop.statut}/>}<div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><Panel title="Ventes des 30 derniers jours"><MiniChart values={values}/></Panel><Panel title="Commandes à traiter" action={<Link href="/mes-commandes-vendeur" className="text-[11px] font-bold text-green-600">Voir tout</Link>}>{pending.length===0?<Empty message="Aucune commande à traiter."/>:<div className="space-y-2">{pending.slice(0,5).map(o=><div key={o.id} className="rounded-xl bg-slate-50 p-3"><div className="flex justify-between gap-2"><div><p className="text-xs font-bold">#{o.id} · {o.buyer.name}</p><p className="mt-1 text-[10px] text-slate-400">{o.items.map(i=>`${i.product.nom} ×${i.quantite}`).join(", ")}</p></div><StatusBadge status={o.statut}/></div>{o.statut==="payee"&&<button onClick={async()=>{await api.put(`/orders/${o.id}/statut`,{statut:"expediee"});setOrders(await api.get("/shop/orders").then(r=>r.data));}} className="mt-2 w-full rounded-lg bg-green-600 py-2 text-[10px] font-bold text-white">Marquer expédiée</button>}</div>)}</div>}</Panel></div><Panel title="Gestion de la boutique"><div className="grid gap-2 sm:grid-cols-3"><Quick href="/mes-produits" icon={<Package size={16}/>} label="Gérer les produits"/><Quick href="/ma-boutique" icon={<Store size={16}/>} label="Ma boutique"/><Quick href="/mes-statistiques" icon={<BarIcon/>} label="Statistiques"/></div></Panel></div>}

function Admin(){const dispatch=useAppDispatch();const {stats,shops}=useAppSelector(s=>s.admin);useEffect(()=>{dispatch(fetchStats());dispatch(fetchAllShops());},[dispatch]);const pending=shops.filter(s=>s.statut==="en_attente");return <div className="space-y-5"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CircleDollarSign size={18}/>} label="Chiffre d'affaires" value={money(stats?.chiffre_affaires_total)} trend="+12%"/><Metric icon={<Users size={18}/>} label="Utilisateurs" value={stats?.total_utilisateurs??0}/><Metric icon={<Store size={18}/>} label="Boutiques actives" value={stats?.total_boutiques??0}/><Metric icon={<ShoppingCart size={18}/>} label="Commandes" value={stats?.total_commandes??0}/></div><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Panel title="Demandes de boutique" action={<Link href="/admin/commissions" className="text-[11px] font-bold text-green-600">Gérer</Link>}>{pending.length===0?<Empty message="Aucune demande en attente."/>:<div className="divide-y divide-slate-100">{pending.slice(0,6).map(s=><div key={s.id} className="flex items-center gap-3 py-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-green-50 text-green-600"><Store size={15}/></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{s.nom}</p><p className="truncate text-[10px] text-slate-400">{s.user.name} · {s.user.email}</p></div><div className="flex gap-1"><button onClick={()=>dispatch(validateShop(s.id))} className="grid h-8 w-8 place-items-center rounded-lg bg-green-600 text-white"><Check size={13}/></button><button onClick={()=>dispatch(refuseShop(s.id))} className="grid h-8 w-8 place-items-center rounded-lg bg-red-50 text-red-500"><X size={13}/></button></div></div>)}</div>}</Panel><Panel title="Raccourcis administration"><div className="space-y-2"><Quick href="/admin/utilisateurs" icon={<Users size={16}/>} label="Utilisateurs"/><Quick href="/admin/commissions" icon={<Store size={16}/>} label="Boutiques & commissions"/><Quick href="/admin/commandes" icon={<ShoppingCart size={16}/>} label="Commandes"/><Quick href="/admin/statistiques" icon={<TrendingUp size={16}/>} label="Statistiques"/></div></Panel></div></div>}

function Metric({icon,label,value,trend}:{icon:React.ReactNode;label:string;value:React.ReactNode;trend?:string}){return <div className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-[11px] font-semibold text-slate-400">{label}</p><p className="mt-2 text-xl font-black tracking-tight text-slate-900">{value}</p>{trend&&<p className="mt-2 inline-flex items-center gap-1 text-[10px] font-bold text-green-600"><ArrowUpRight size={11}/>{trend} ce mois</p>}</div><div className="grid h-10 w-10 place-items-center rounded-xl bg-green-50 text-green-600">{icon}</div></div></div>}
function Panel({title,children,action}:{title:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="text-sm font-extrabold text-slate-900">{title}</h2>{action}</div>{children}</section>}
function Quick({href,icon,label}:{href:string;icon:React.ReactNode;label:string}){return <Link href={href} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-xs font-bold text-slate-600 hover:border-green-100 hover:bg-green-50 hover:text-green-700"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-50 text-slate-500">{icon}</span>{label}<ChevronRight size={13} className="ml-auto text-slate-300"/></Link>}
function Empty({message,href}:{message:string;href?:string}){return <div className="py-8 text-center text-xs text-slate-400">{message}{href&&<Link href={href} className="ml-1 font-bold text-green-600">Découvrir</Link>}</div>}
function Notice({title,text,href,action,tone="en_attente"}:{title:string;text:string;href?:string;action?:string;tone?:string}){const good=tone==="valide";const bad=tone==="refuse";return <div className={`flex flex-col gap-3 rounded-2xl border p-4 sm:flex-row sm:items-center ${good?"border-green-100 bg-green-50/60":bad?"border-red-100 bg-red-50/60":"border-amber-100 bg-amber-50/60"}`}><div className="flex-1"><p className="text-xs font-extrabold">{title}</p><p className="mt-1 text-[11px] text-slate-500">{text}</p></div>{href&&<Link href={href} className="rounded-xl bg-green-600 px-3 py-2 text-[10px] font-bold text-white">{action}</Link>}</div>}
function MiniChart({values}:{values:number[]}){const max=Math.max(...values);const points=values.map((v,i)=>`${(i/(values.length-1))*100},${100-(v/max)*78}`).join(" ");return <div><div className="relative h-56 overflow-hidden rounded-xl bg-slate-50"><div className="absolute inset-x-0 top-1/4 border-t border-dashed border-slate-200"/><div className="absolute inset-x-0 top-1/2 border-t border-dashed border-slate-200"/><div className="absolute inset-x-0 top-3/4 border-t border-dashed border-slate-200"/><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="absolute inset-0 h-full w-full p-4"><polyline fill="none" stroke="currentColor" strokeWidth="1.4" points={points} className="text-green-500"/><polygon fill="currentColor" fillOpacity=".08" points={`0,100 ${points} 100,100`} className="text-green-500"/></svg></div><div className="mt-3 flex justify-between text-[9px] text-slate-400"><span>J-30</span><span>J-20</span><span>J-10</span><span>Aujourd'hui</span></div></div>}
function BarIcon(){return <TrendingUp size={16}/>}
